name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    # These permissions are needed for GitHub Pages deployment
    permissions:
      contents: write
      pages: write
      id-token: write

    # Environment for GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Need to checkout the repository first
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      # Add base path configuration for GitHub Pages
      - name: Configure for GitHub Pages
        run: |
          echo "Setting base path for GitHub Pages deployment"
          # Create or update vite.config.js to include base path
          if [ ! -f "dist/index.html" ]; then
            echo "Build files not found"
            exit 1
          fi

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Use the built-in GitHub Pages deployment
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Deploy to GitHub Pages [skip ci]"
          git-config-name: ${{ github.repository_owner }}
          git-config-email: ${{ github.repository_owner }}@users.noreply.github.com
          force: true

